#!/bin/bash
# Modal GitHub Secrets 配置指南
#
# 请按照以下步骤在 GitHub 网页上配置 Secrets

echo "╔══════════════════════════════════════════════════════════╗"
echo "║         Modal GitHub Secrets 配置指南                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📌 步骤 1: 打开 GitHub Secrets 页面"
echo ""
echo "   点击打开:"
echo "   https://github.com/w932635477-bit/WhyFire/settings/secrets/actions"
echo ""
echo "   或者手动导航:"
echo "   Repository → Settings → Secrets and variables → Actions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 步骤 2: 添加 MODAL_TOKEN_ID"
echo ""
echo "   点击 'New repository secret'"
echo ""
echo "   Name:  MODAL_TOKEN_ID"
echo "   Value: wk-3d711yJxxELjvUfKhlvb6s"
echo ""
echo "   点击 'Add secret'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 步骤 3: 添加 MODAL_TOKEN_SECRET"
echo ""
echo "   再次点击 'New repository secret'"
echo ""
echo "   Name:  MODAL_TOKEN_SECRET"
echo "   Value: ws-9ST1xQzH77kB5pBqYjXDdl"
echo ""
echo "   点击 'Add secret'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 步骤 4: 触发部署"
echo ""
echo "   打开:"
echo "   https://github.com/w932635477-bit/WhyFire/actions/workflows/deploy-modal.yml"
echo ""
echo "   点击 'Run workflow' → 'Run workflow'"
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  配置完成后，回复 'done' 我会帮你验证部署结果           ║"
echo "╚══════════════════════════════════════════════════════════╝"

# 尝试打开浏览器
if command -v open &> /dev/null; then
    echo ""
    read -p "按 Enter 打开 GitHub Secrets 页面..."
    open "https://github.com/w932635477-bit/WhyFire/settings/secrets/actions"
fi
